"""Create client, scope, and client_scope tables

Revision ID: 56ff0bfb8813
Revises:
Create Date: 2026-07-24 16:26:42.298975

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56ff0bfb8813"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### cusotom commands ###
    op.execute("CREATE SCHEMA oauth2")
    # ### end cusotom commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column(
            "client_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="The identifier of the confidential client, different from the `id`.",
        ),
        sa.Column(
            "client_secret",
            sa.String(length=255),
            nullable=False,
            comment="Hashed secret of the client.",
        ),
        sa.Column(
            "client_name",
            sa.String(length=63),
            nullable=False,
            comment="Just a name for debugging purposes, no logic should be created upon it.",
        ),
        sa.Column(
            "client_email",
            sa.String(length=255),
            nullable=False,
            comment="Needed to inform the client about events, e.g. password rotation.",
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", name="clientstatusenum"),
            server_default="ACTIVE",
            nullable=False,
            comment="Can disable some clients.",
        ),
        sa.Column(
            "token_endpoint_auth_method",
            sa.Enum(
                "CLIENT_SECRET_BASIC",
                "CLIENT_SECRET_POST",
                name="clienttokenendpointauthmethodenum",
            ),
            server_default="CLIENT_SECRET_BASIC",
            nullable=False,
            comment="Specify different ways a confidential client can authenticate itself.",
        ),
        sa.Column(
            "last_secret_rotation",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Recording the credential rotation time, as an security operational practice.",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the record was last modified",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
        schema="oauth2",
    )
    op.create_index(
        "client_client_id_status_idx",
        "client",
        ["client_id", "status"],
        unique=False,
        schema="oauth2",
    )
    op.create_table(
        "scope",
        sa.Column(
            "scope_name",
            sa.String(length=255),
            nullable=False,
            comment="Space-delimited and case-sensitive. e.g. article:read.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Human-readable explanation of the scope, for future UI admin.",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the record was last modified",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope_name"),
        schema="oauth2",
    )
    op.create_index(
        "scope_scope_name_idx", "scope", ["scope_name"], unique=False, schema="oauth2"
    )
    op.create_table(
        "client_scope",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the record was last modified",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["oauth2.client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["oauth2.scope.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "scope_id", name="client_scope_ids_uix"),
        schema="oauth2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("client_scope", schema="oauth2")
    op.drop_index("scope_scope_name_idx", table_name="scope", schema="oauth2")
    op.drop_table("scope", schema="oauth2")
    op.drop_index("client_client_id_status_idx", table_name="client", schema="oauth2")
    op.drop_table("client", schema="oauth2")
    # ### end Alembic commands ###

    # ### cusotom commands ###
    op.execute("DROP SCHEMA oauth2")
    # ### end cusotom commands ###
