"""Alter initial_access_token.token_hash with a longer string

Revision ID: 60362e687317
Revises: 9f342817b986
Create Date: 2026-08-16 18:25:09.511852

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60362e687317"
down_revision: Union[str, Sequence[str], None] = "9f342817b986"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initial_access_token",
        "token_hash",
        existing_type=sa.VARCHAR(length=63),
        type_=sa.String(length=255),
        existing_comment="Hashed initial access token, included in client registration request.",
        existing_nullable=False,
        schema="oauth2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initial_access_token",
        "token_hash",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=63),
        existing_comment="Hashed initial access token, included in client registration request.",
        existing_nullable=False,
        schema="oauth2",
    )
    # ### end Alembic commands ###
