"""Create unique constraint for client.client_name

Revision ID: 6cb26296434a
Revises: 7fa74525ffb5
Create Date: 2026-08-04 18:44:51.719832

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cb26296434a"
down_revision: Union[str, Sequence[str], None] = "7fa74525ffb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "client", ["client_name"], schema="oauth2")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "client", schema="oauth2", type_="unique")
    # ### end Alembic commands ###
