"""Alter client table with new columns and constraints

Revision ID: 7fa74525ffb5
Revises: 56ff0bfb8813
Create Date: 2026-07-25 17:34:01.906420

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fa74525ffb5"
down_revision: Union[str, Sequence[str], None] = "56ff0bfb8813"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "client_uri",
            sa.Text(),
            nullable=True,
            comment="A link to the client's website.",
        ),
        schema="oauth2",
    )
    op.add_column(
        "client",
        sa.Column(
            "logo_uri",
            sa.Text(),
            nullable=True,
            comment="A link to the client's logo picture.",
        ),
        schema="oauth2",
    )
    op.add_column(
        "client",
        sa.Column(
            "tos_uri",
            sa.Text(),
            nullable=True,
            comment="A link to the client's terms of service page.",
        ),
        schema="oauth2",
    )
    op.add_column(
        "client",
        sa.Column(
            "policy_uri",
            sa.Text(),
            nullable=True,
            comment="A link to the client's policy page.",
        ),
        schema="oauth2",
    )
    op.add_column(
        "client",
        sa.Column(
            "software_id",
            sa.String(length=255),
            nullable=True,
            comment="An identifier for the software. This is different compare to client_id, where client_id represents each software process. This has nothing to do with the business logic.",
        ),
        schema="oauth2",
    )
    op.add_column(
        "client",
        sa.Column(
            "software_version",
            sa.String(length=255),
            nullable=True,
            comment="A version for the software",
        ),
        schema="oauth2",
    )
    op.add_column(
        "client",
        sa.Column(
            "grant_types",
            postgresql.ARRAY(
                sa.Enum("CLIENT_CREDENTIALS", name="granttypeenum", native_enum=False)
            ),
            server_default="{client_credentials}",
            nullable=False,
            comment="Answer to what grant types do the client support.",
        ),
        schema="oauth2",
    )
    op.add_column(
        "client",
        sa.Column(
            "redirect_uris",
            postgresql.ARRAY(sa.TEXT()),
            nullable=False,
            comment="Mandatory redirect uris",
        ),
        schema="oauth2",
    )
    op.add_column(
        "client",
        sa.Column(
            "response_types",
            postgresql.ARRAY(
                sa.Enum("CODE", "TOKEN", name="responsetypeenum", native_enum=False)
            ),
            server_default="{code}",
            nullable=False,
            comment="Which response types the authorization endpoint it will use.",
        ),
        schema="oauth2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "response_types", schema="oauth2")
    op.drop_column("client", "redirect_uris", schema="oauth2")
    op.drop_column("client", "grant_types", schema="oauth2")
    op.drop_column("client", "software_version", schema="oauth2")
    op.drop_column("client", "software_id", schema="oauth2")
    op.drop_column("client", "policy_uri", schema="oauth2")
    op.drop_column("client", "tos_uri", schema="oauth2")
    op.drop_column("client", "logo_uri", schema="oauth2")
    op.drop_column("client", "client_uri", schema="oauth2")
    # ### end Alembic commands ###
