"""Add on_delete=RESTRICT for client_scope.scope_id.

Revision ID: 8b06f51ad122
Revises: 6cb26296434a
Create Date: 2026-08-16 14:25:41.988579

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b06f51ad122"
down_revision: Union[str, Sequence[str], None] = "6cb26296434a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("client_scope_scope_id_fkey"),
        "client_scope",
        schema="oauth2",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "client_scope",
        "scope",
        ["scope_id"],
        ["id"],
        source_schema="oauth2",
        referent_schema="oauth2",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "client_scope", schema="oauth2", type_="foreignkey")
    op.create_foreign_key(
        op.f("client_scope_scope_id_fkey"),
        "client_scope",
        "scope",
        ["scope_id"],
        ["id"],
        source_schema="oauth2",
        referent_schema="oauth2",
    )
    # ### end Alembic commands ###
