"""Make initial_acces_token.expires_at timezone-aware

Revision ID: 9f342817b986
Revises: cea28416197a
Create Date: 2026-08-16 18:22:05.613324

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f342817b986"
down_revision: Union[str, Sequence[str], None] = "cea28416197a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initial_access_token",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Set a expiration time for token, avoiding long-term abuse.",
        existing_nullable=False,
        schema="oauth2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initial_access_token",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="Set a expiration time for token, avoiding long-term abuse.",
        existing_nullable=False,
        schema="oauth2",
    )
    # ### end Alembic commands ###
