"""Create initial_access_token

Revision ID: cea28416197a
Revises: 8b06f51ad122
Create Date: 2026-08-16 14:33:13.037054

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cea28416197a"
down_revision: Union[str, Sequence[str], None] = "8b06f51ad122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initial_access_token",
        sa.Column(
            "token_hash",
            sa.String(length=63),
            nullable=False,
            comment="Hashed initial access token, included in client registration request.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=False,
            comment="Set a expiration time for token, avoiding long-term abuse.",
        ),
        sa.Column(
            "max_registration",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="A limit for the times user can use the token to create clients.",
        ),
        sa.Column(
            "registrations_used",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Times user has used the token. It should never get above `max_registration`.",
        ),
        sa.Column(
            "note",
            sa.Text(),
            nullable=True,
            comment="A note helping the admin or the end-user itself.",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the record was last modified",
        ),
        sa.CheckConstraint("expires_at > now()"),
        sa.CheckConstraint("max_registration >= registrations_used"),
        sa.PrimaryKeyConstraint("id"),
        schema="oauth2",
    )
    op.create_index(
        op.f("ix_oauth2_initial_access_token_expires_at"),
        "initial_access_token",
        ["expires_at"],
        unique=False,
        schema="oauth2",
    )
    op.create_index(
        op.f("ix_oauth2_initial_access_token_token_hash"),
        "initial_access_token",
        ["token_hash"],
        unique=True,
        schema="oauth2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_oauth2_initial_access_token_token_hash"),
        table_name="initial_access_token",
        schema="oauth2",
    )
    op.drop_index(
        op.f("ix_oauth2_initial_access_token_expires_at"),
        table_name="initial_access_token",
        schema="oauth2",
    )
    op.drop_table("initial_access_token", schema="oauth2")
    # ### end Alembic commands ###
