"""Create oauth2.client

Revision ID: 8474d6904ca2
Revises:
Create Date: 2026-06-13 16:44:48.528318

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8474d6904ca2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands manually created. ###
    op.execute("CREATE SCHEMA oauth2")
    # ### end of manual commands. ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column(
            "client_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="The identifier of the confidential client, different from the `id`.",
        ),
        sa.Column(
            "client_secret",
            sa.String(length=255),
            nullable=False,
            comment="Hashed secret of the client.",
        ),
        sa.Column(
            "client_name",
            sa.String(length=63),
            nullable=False,
            comment="Just a name for debugging purposes, no logic should be created upon it.",
        ),
        sa.Column(
            "client_email",
            sa.String(length=255),
            nullable=False,
            comment="Needed to inform the client about events, e.g. password rotation.",
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", name="clientstatusenum"),
            server_default="ACTIVE",
            nullable=False,
            comment="Can disable some clients.",
        ),
        sa.Column(
            "token_endpoint_auth_method",
            sa.Enum(
                "CLIENT_SECRET_BASIC",
                "CLIENT_SECRET_POST",
                name="clienttokenendpointauthmethod",
            ),
            server_default="CLIENT_SECRET_BASIC",
            nullable=False,
            comment="Specify different ways a confidential client can authenticate itself.",
        ),
        sa.Column(
            "last_secret_rotation",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Recording the credential rotation time, as an security operational practice.",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing primary key",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the record was last modified",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
        schema="oauth2",
    )
    op.create_index(
        "client_client_id_status_idx",
        "client",
        ["client_id", "status"],
        unique=False,
        schema="oauth2",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("client_client_id_status_idx", table_name="client", schema="oauth2")
    op.drop_table("client", schema="oauth2")
    # ### end Alembic commands ###

    # ### commands manually created. ###
    op.execute("DROP SCHEMA oauth2")
    # ### end of manual commands. ###
